export const planets = [
  {
    id: 1,
    name: 'Introdução',
    image: require('../assets/PlanetAssets/planet-image-1.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-1.svg').default,
    stars: [
      {
        id: 1,
        name: 'Lógica e algoritmos',
        number: 1,
        isChallenge: false,
      },
      {
        id: 2,
        name: 'Escreva e leia',
        number: 2,
        isChallenge: false,
      },
      {
        id: 3,
        name: 'Variáveis',
        number: 3,
        isChallenge: false,
      },
      {
        id: 4,
        name: 'Desafio: Enviar mensagem',
        number: 4,
        isChallenge: true,
      },
    ],
  },
  {
    id: 2,
    name: 'Variáveis',
    image: require('../assets/PlanetAssets/planet-image-2.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-2.svg').default,
    stars: [
      {
        id: 5,
        name: 'Declaração e atribuição',
        number: 1,
        isChallenge: false,
      },
      {
        id: 6,
        name: 'Caracteres',
        number: 2,
        isChallenge: false,
      },
      {
        id: 7,
        name: 'Inteiros e Reais',
        number: 3,
        isChallenge: false,
      },
      {
        id: 8,
        name: 'Lógicos',
        number: 4,
        isChallenge: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Variáveis',
    image: require('../assets/PlanetAssets/planet-image-3.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-3.svg').default,
    stars: [],
  },
  {
    id: 4,
    name: 'Operadores',
    image: require('../assets/PlanetAssets/planet-image-4.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-4.svg').default,
    stars: [],
  },
  {
    id: 5,
    name: 'Estrutura condicional',
    image: require('../assets/PlanetAssets/planet-image-5.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-5.svg').default,
    stars: [],
  },
  {
    id: 6,
    name: 'Estrutura de repetição',
    image: require('../assets/PlanetAssets/planet-image-6.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-6.svg').default,
    stars: [],
  },
  {
    id: 7,
    name: 'Vetores',
    image: require('../assets/PlanetAssets/planet-image-7.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-7.svg').default,
    stars: [],
  },
  {
    id: 8,
    name: 'Matrizes',
    image: require('../assets/PlanetAssets/planet-image-8.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-8.svg').default,
    stars: [],
  },
  {
    id: 9,
    name: 'Funções',
    image: require('../assets/PlanetAssets/planet-image-9.svg').default,
    icon: require('../assets/PlanetAssets/planet-icon-9.svg').default,
    stars: [],
  },
];
